[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-webgl-fun"
version = "0.0.1"
dependencies = [
    "fastapi",
]
requires-python = ">= 3.10"
description = "A simple project of WebGL webpages served via FastAPI"
readme = "README.md"